// <auto-generated />
namespace MvcMovie.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DropGenre : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DropGenre));
        
        string IMigrationMetadata.Id
        {
            get { return "201305140242573_DropGenre"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
